export const spriteSheetMap = {
  "autumn tilemap": {
    "autumn tilemap-0": "autumn tilemap-0.png",
    "autumn tilemap-1": "autumn tilemap-1.png",
    "autumn tilemap-2": "autumn tilemap-2.png",
    "autumn tilemap-3": "autumn tilemap-3.png",
    "autumn tilemap-4": "autumn tilemap-4.png",
    "autumn tilemap-5": "autumn tilemap-5.png",
    "autumn tilemap-6": "autumn tilemap-6.png",
    "autumn tilemap-7": "autumn tilemap-7.png",
    "autumn tilemap-8": "autumn tilemap-8.png",
    "autumn tilemap-9": "autumn tilemap-9.png",
    "autumn tilemap-10": "autumn tilemap-10.png",
    "autumn tilemap-11": "autumn tilemap-11.png",
    "autumn tilemap-12": "autumn tilemap-12.png",
    "autumn tilemap-13": "autumn tilemap-13.png",
    "autumn tilemap-14": "autumn tilemap-14.png",
    "autumn tilemap-15": "autumn tilemap-15.png",
    "autumn tilemap-16": "autumn tilemap-16.png",
    "autumn tilemap-17": "autumn tilemap-17.png",
    "autumn tilemap-18": "autumn tilemap-18.png",
    "autumn tilemap-19": "autumn tilemap-19.png",
    "autumn tilemap-20": "autumn tilemap-20.png",
    "autumn tilemap-21": "autumn tilemap-21.png",
    "autumn tilemap-22": "autumn tilemap-22.png",
    "autumn tilemap-23": "autumn tilemap-23.png",
    "autumn tilemap-24": "autumn tilemap-24.png",
    "autumn tilemap-25": "autumn tilemap-25.png",
    "autumn tilemap-26": "autumn tilemap-26.png",
    "autumn tilemap-27": "autumn tilemap-27.png",
    "autumn tilemap-28": "autumn tilemap-28.png",
    "autumn tilemap-29": "autumn tilemap-29.png",
    "autumn tilemap-30": "autumn tilemap-30.png",
    "autumn tilemap-31": "autumn tilemap-31.png",
    "autumn tilemap-32": "autumn tilemap-32.png",
    "autumn tilemap-33": "autumn tilemap-33.png",
    "autumn tilemap-34": "autumn tilemap-34.png",
    "autumn tilemap-35": "autumn tilemap-35.png",
    "autumn tilemap-36": "autumn tilemap-36.png",
    "autumn tilemap-37": "autumn tilemap-37.png",
    "autumn tilemap-38": "autumn tilemap-38.png",
    "autumn tilemap-39": "autumn tilemap-39.png",
    "autumn tilemap-40": "autumn tilemap-40.png",
    "autumn tilemap-41": "autumn tilemap-41.png",
    "autumn tilemap-42": "autumn tilemap-42.png",
    "autumn tilemap-43": "autumn tilemap-43.png",
    "autumn tilemap-44": "autumn tilemap-44.png",
    "autumn tilemap-45": "autumn tilemap-45.png",
    "autumn tilemap-46": "autumn tilemap-46.png",
    "autumn tilemap-47": "autumn tilemap-47.png",
    "autumn tilemap-48": "autumn tilemap-48.png",
    "autumn tilemap-49": "autumn tilemap-49.png",
    "autumn tilemap-50": "autumn tilemap-50.png",
    "autumn tilemap-51": "autumn tilemap-51.png",
    "autumn tilemap-52": "autumn tilemap-52.png",
    "autumn tilemap-53": "autumn tilemap-53.png",
    "autumn tilemap-54": "autumn tilemap-54.png",
    "autumn tilemap-55": "autumn tilemap-55.png",
    "autumn tilemap-56": "autumn tilemap-56.png",
    "autumn tilemap-57": "autumn tilemap-57.png",
    "autumn tilemap-58": "autumn tilemap-58.png",
    "autumn tilemap-59": "autumn tilemap-59.png",
    "autumn tilemap-60": "autumn tilemap-60.png",
    "autumn tilemap-61": "autumn tilemap-61.png",
    "autumn tilemap-62": "autumn tilemap-62.png",
    "autumn tilemap-63": "autumn tilemap-63.png",
    "autumn tilemap-64": "autumn tilemap-64.png",
    "autumn tilemap-65": "autumn tilemap-65.png",
    "autumn tilemap-66": "autumn tilemap-66.png",
    "autumn tilemap-67": "autumn tilemap-67.png",
    "autumn tilemap-68": "autumn tilemap-68.png",
    "autumn tilemap-69": "autumn tilemap-69.png",
    "autumn tilemap-70": "autumn tilemap-70.png",
    "autumn tilemap-71": "autumn tilemap-71.png",
    "autumn tilemap-72": "autumn tilemap-72.png",
    "autumn tilemap-73": "autumn tilemap-73.png",
    "autumn tilemap-74": "autumn tilemap-74.png",
    "autumn tilemap-75": "autumn tilemap-75.png",
    "autumn tilemap-76": "autumn tilemap-76.png",
    "autumn tilemap-77": "autumn tilemap-77.png",
    "autumn tilemap-78": "autumn tilemap-78.png",
    "autumn tilemap-79": "autumn tilemap-79.png",
    "autumn tilemap-80": "autumn tilemap-80.png",
    "autumn tilemap-81": "autumn tilemap-81.png",
    "autumn tilemap-82": "autumn tilemap-82.png",
    "autumn tilemap-83": "autumn tilemap-83.png",
    "autumn tilemap-84": "autumn tilemap-84.png",
    "autumn tilemap-85": "autumn tilemap-85.png",
    "autumn tilemap-86": "autumn tilemap-86.png",
    "autumn tilemap-87": "autumn tilemap-87.png",
    "autumn tilemap-88": "autumn tilemap-88.png",
    "autumn tilemap-89": "autumn tilemap-89.png",
    "autumn tilemap-90": "autumn tilemap-90.png",
    "autumn tilemap-91": "autumn tilemap-91.png",
    "autumn tilemap-92": "autumn tilemap-92.png",
    "autumn tilemap-93": "autumn tilemap-93.png",
    "autumn tilemap-94": "autumn tilemap-94.png",
    "autumn tilemap-95": "autumn tilemap-95.png",
    "autumn tilemap-96": "autumn tilemap-96.png",
    "autumn tilemap-97": "autumn tilemap-97.png",
    "autumn tilemap-98": "autumn tilemap-98.png",
    "autumn tilemap-99": "autumn tilemap-99.png",
    "autumn tilemap-100": "autumn tilemap-100.png",
    "autumn tilemap-101": "autumn tilemap-101.png",
    "autumn tilemap-102": "autumn tilemap-102.png",
    "autumn tilemap-103": "autumn tilemap-103.png",
    "autumn tilemap-104": "autumn tilemap-104.png",
    "autumn tilemap-105": "autumn tilemap-105.png",
    "autumn tilemap-106": "autumn tilemap-106.png",
    "autumn tilemap-107": "autumn tilemap-107.png",
    "autumn tilemap-108": "autumn tilemap-108.png",
  },
  inside: {
    "inside-0": "inside-0.png",
    "inside-1": "inside-1.png",
    "inside-2": "inside-2.png",
    "inside-3": "inside-3.png",
    "inside-4": "inside-4.png",
    "inside-5": "inside-5.png",
    "inside-6": "inside-6.png",
    "inside-7": "inside-7.png",
    "inside-8": "inside-8.png",
    "inside-9": "inside-9.png",
    "inside-10": "inside-10.png",
    "inside-11": "inside-11.png",
    "inside-12": "inside-12.png",
    "inside-13": "inside-13.png",
    "inside-14": "inside-14.png",
    "inside-15": "inside-15.png",
    "inside-16": "inside-16.png",
    "inside-17": "inside-17.png",
    "inside-18": "inside-18.png",
    "inside-19": "inside-19.png",
    "inside-20": "inside-20.png",
    "inside-21": "inside-21.png",
    "inside-22": "inside-22.png",
    "inside-23": "inside-23.png",
    "inside-24": "inside-24.png",
    "inside-25": "inside-25.png",
    "inside-26": "inside-26.png",
    "inside-27": "inside-27.png",
    "inside-28": "inside-28.png",
    "inside-29": "inside-29.png",
    "inside-30": "inside-30.png",
    "inside-31": "inside-31.png",
    "inside-32": "inside-32.png",
    "inside-33": "inside-33.png",
    "inside-34": "inside-34.png",
    "inside-35": "inside-35.png",
    "inside-36": "inside-36.png",
    "inside-37": "inside-37.png",
    "inside-38": "inside-38.png",
    "inside-39": "inside-39.png",
    "inside-40": "inside-40.png",
    "inside-41": "inside-41.png",
    "inside-42": "inside-42.png",
    "inside-43": "inside-43.png",
    "inside-44": "inside-44.png",
    "inside-45": "inside-45.png",
    "inside-46": "inside-46.png",
    "inside-47": "inside-47.png",
    "inside-48": "inside-48.png",
    "inside-49": "inside-49.png",
    "inside-50": "inside-50.png",
  },
  "spring tilemap": {
    "spring tilemap-0": "spring tilemap-0.png",
    "spring tilemap-1": "spring tilemap-1.png",
    "spring tilemap-2": "spring tilemap-2.png",
    "spring tilemap-3": "spring tilemap-3.png",
    "spring tilemap-4": "spring tilemap-4.png",
    "spring tilemap-5": "spring tilemap-5.png",
    "spring tilemap-6": "spring tilemap-6.png",
    "spring tilemap-7": "spring tilemap-7.png",
    "spring tilemap-8": "spring tilemap-8.png",
    "spring tilemap-9": "spring tilemap-9.png",
    "spring tilemap-10": "spring tilemap-10.png",
    "spring tilemap-11": "spring tilemap-11.png",
    "spring tilemap-12": "spring tilemap-12.png",
    "spring tilemap-13": "spring tilemap-13.png",
    "spring tilemap-14": "spring tilemap-14.png",
    "spring tilemap-15": "spring tilemap-15.png",
    "spring tilemap-16": "spring tilemap-16.png",
    "spring tilemap-17": "spring tilemap-17.png",
    "spring tilemap-18": "spring tilemap-18.png",
    "spring tilemap-19": "spring tilemap-19.png",
    "spring tilemap-20": "spring tilemap-20.png",
    "spring tilemap-21": "spring tilemap-21.png",
    "spring tilemap-22": "spring tilemap-22.png",
    "spring tilemap-23": "spring tilemap-23.png",
    "spring tilemap-24": "spring tilemap-24.png",
    "spring tilemap-25": "spring tilemap-25.png",
    "spring tilemap-26": "spring tilemap-26.png",
    "spring tilemap-27": "spring tilemap-27.png",
    "spring tilemap-28": "spring tilemap-28.png",
    "spring tilemap-29": "spring tilemap-29.png",
    "spring tilemap-30": "spring tilemap-30.png",
    "spring tilemap-31": "spring tilemap-31.png",
    "spring tilemap-32": "spring tilemap-32.png",
    "spring tilemap-33": "spring tilemap-33.png",
    "spring tilemap-34": "spring tilemap-34.png",
    "spring tilemap-35": "spring tilemap-35.png",
    "spring tilemap-36": "spring tilemap-36.png",
    "spring tilemap-37": "spring tilemap-37.png",
    "spring tilemap-38": "spring tilemap-38.png",
    "spring tilemap-39": "spring tilemap-39.png",
    "spring tilemap-40": "spring tilemap-40.png",
    "spring tilemap-41": "spring tilemap-41.png",
    "spring tilemap-42": "spring tilemap-42.png",
    "spring tilemap-43": "spring tilemap-43.png",
    "spring tilemap-44": "spring tilemap-44.png",
    "spring tilemap-45": "spring tilemap-45.png",
    "spring tilemap-46": "spring tilemap-46.png",
    "spring tilemap-47": "spring tilemap-47.png",
    "spring tilemap-48": "spring tilemap-48.png",
    "spring tilemap-49": "spring tilemap-49.png",
    "spring tilemap-50": "spring tilemap-50.png",
    "spring tilemap-51": "spring tilemap-51.png",
    "spring tilemap-52": "spring tilemap-52.png",
    "spring tilemap-53": "spring tilemap-53.png",
    "spring tilemap-54": "spring tilemap-54.png",
    "spring tilemap-55": "spring tilemap-55.png",
    "spring tilemap-56": "spring tilemap-56.png",
    "spring tilemap-57": "spring tilemap-57.png",
    "spring tilemap-58": "spring tilemap-58.png",
    "spring tilemap-59": "spring tilemap-59.png",
    "spring tilemap-60": "spring tilemap-60.png",
    "spring tilemap-61": "spring tilemap-61.png",
    "spring tilemap-62": "spring tilemap-62.png",
    "spring tilemap-63": "spring tilemap-63.png",
    "spring tilemap-64": "spring tilemap-64.png",
    "spring tilemap-65": "spring tilemap-65.png",
    "spring tilemap-66": "spring tilemap-66.png",
    "spring tilemap-67": "spring tilemap-67.png",
    "spring tilemap-68": "spring tilemap-68.png",
    "spring tilemap-69": "spring tilemap-69.png",
    "spring tilemap-70": "spring tilemap-70.png",
    "spring tilemap-71": "spring tilemap-71.png",
    "spring tilemap-72": "spring tilemap-72.png",
    "spring tilemap-73": "spring tilemap-73.png",
    "spring tilemap-74": "spring tilemap-74.png",
    "spring tilemap-75": "spring tilemap-75.png",
    "spring tilemap-76": "spring tilemap-76.png",
    "spring tilemap-77": "spring tilemap-77.png",
    "spring tilemap-78": "spring tilemap-78.png",
    "spring tilemap-79": "spring tilemap-79.png",
    "spring tilemap-80": "spring tilemap-80.png",
    "spring tilemap-81": "spring tilemap-81.png",
    "spring tilemap-82": "spring tilemap-82.png",
    "spring tilemap-83": "spring tilemap-83.png",
    "spring tilemap-84": "spring tilemap-84.png",
    "spring tilemap-85": "spring tilemap-85.png",
    "spring tilemap-86": "spring tilemap-86.png",
    "spring tilemap-87": "spring tilemap-87.png",
    "spring tilemap-88": "spring tilemap-88.png",
    "spring tilemap-89": "spring tilemap-89.png",
    "spring tilemap-90": "spring tilemap-90.png",
    "spring tilemap-91": "spring tilemap-91.png",
    "spring tilemap-92": "spring tilemap-92.png",
    "spring tilemap-93": "spring tilemap-93.png",
    "spring tilemap-94": "spring tilemap-94.png",
    "spring tilemap-95": "spring tilemap-95.png",
    "spring tilemap-96": "spring tilemap-96.png",
    "spring tilemap-97": "spring tilemap-97.png",
    "spring tilemap-98": "spring tilemap-98.png",
    "spring tilemap-99": "spring tilemap-99.png",
    "spring tilemap-100": "spring tilemap-100.png",
    "spring tilemap-101": "spring tilemap-101.png",
    "spring tilemap-102": "spring tilemap-102.png",
    "spring tilemap-103": "spring tilemap-103.png",
    "spring tilemap-104": "spring tilemap-104.png",
    "spring tilemap-105": "spring tilemap-105.png",
    "spring tilemap-106": "spring tilemap-106.png",
    "spring tilemap-107": "spring tilemap-107.png",
    "spring tilemap-108": "spring tilemap-108.png",
  },
  "summer tilemap": {
    "summer tilemap-0": "summer tilemap-0.png",
    "summer tilemap-1": "summer tilemap-1.png",
    "summer tilemap-2": "summer tilemap-2.png",
    "summer tilemap-3": "summer tilemap-3.png",
    "summer tilemap-4": "summer tilemap-4.png",
    "summer tilemap-5": "summer tilemap-5.png",
    "summer tilemap-6": "summer tilemap-6.png",
    "summer tilemap-7": "summer tilemap-7.png",
    "summer tilemap-8": "summer tilemap-8.png",
    "summer tilemap-9": "summer tilemap-9.png",
    "summer tilemap-10": "summer tilemap-10.png",
    "summer tilemap-11": "summer tilemap-11.png",
    "summer tilemap-12": "summer tilemap-12.png",
    "summer tilemap-13": "summer tilemap-13.png",
    "summer tilemap-14": "summer tilemap-14.png",
    "summer tilemap-15": "summer tilemap-15.png",
    "summer tilemap-16": "summer tilemap-16.png",
    "summer tilemap-17": "summer tilemap-17.png",
    "summer tilemap-18": "summer tilemap-18.png",
    "summer tilemap-19": "summer tilemap-19.png",
    "summer tilemap-20": "summer tilemap-20.png",
    "summer tilemap-21": "summer tilemap-21.png",
    "summer tilemap-22": "summer tilemap-22.png",
    "summer tilemap-23": "summer tilemap-23.png",
    "summer tilemap-24": "summer tilemap-24.png",
    "summer tilemap-25": "summer tilemap-25.png",
    "summer tilemap-26": "summer tilemap-26.png",
    "summer tilemap-27": "summer tilemap-27.png",
    "summer tilemap-28": "summer tilemap-28.png",
    "summer tilemap-29": "summer tilemap-29.png",
    "summer tilemap-30": "summer tilemap-30.png",
    "summer tilemap-31": "summer tilemap-31.png",
    "summer tilemap-32": "summer tilemap-32.png",
    "summer tilemap-33": "summer tilemap-33.png",
    "summer tilemap-34": "summer tilemap-34.png",
    "summer tilemap-35": "summer tilemap-35.png",
    "summer tilemap-36": "summer tilemap-36.png",
    "summer tilemap-37": "summer tilemap-37.png",
    "summer tilemap-38": "summer tilemap-38.png",
    "summer tilemap-39": "summer tilemap-39.png",
    "summer tilemap-40": "summer tilemap-40.png",
    "summer tilemap-41": "summer tilemap-41.png",
    "summer tilemap-42": "summer tilemap-42.png",
    "summer tilemap-43": "summer tilemap-43.png",
    "summer tilemap-44": "summer tilemap-44.png",
    "summer tilemap-45": "summer tilemap-45.png",
    "summer tilemap-46": "summer tilemap-46.png",
    "summer tilemap-47": "summer tilemap-47.png",
    "summer tilemap-48": "summer tilemap-48.png",
    "summer tilemap-49": "summer tilemap-49.png",
    "summer tilemap-50": "summer tilemap-50.png",
    "summer tilemap-51": "summer tilemap-51.png",
    "summer tilemap-52": "summer tilemap-52.png",
    "summer tilemap-53": "summer tilemap-53.png",
    "summer tilemap-54": "summer tilemap-54.png",
    "summer tilemap-55": "summer tilemap-55.png",
    "summer tilemap-56": "summer tilemap-56.png",
    "summer tilemap-57": "summer tilemap-57.png",
    "summer tilemap-58": "summer tilemap-58.png",
    "summer tilemap-59": "summer tilemap-59.png",
    "summer tilemap-60": "summer tilemap-60.png",
    "summer tilemap-61": "summer tilemap-61.png",
    "summer tilemap-62": "summer tilemap-62.png",
    "summer tilemap-63": "summer tilemap-63.png",
    "summer tilemap-64": "summer tilemap-64.png",
    "summer tilemap-65": "summer tilemap-65.png",
    "summer tilemap-66": "summer tilemap-66.png",
    "summer tilemap-67": "summer tilemap-67.png",
    "summer tilemap-68": "summer tilemap-68.png",
    "summer tilemap-69": "summer tilemap-69.png",
    "summer tilemap-70": "summer tilemap-70.png",
    "summer tilemap-71": "summer tilemap-71.png",
    "summer tilemap-72": "summer tilemap-72.png",
    "summer tilemap-73": "summer tilemap-73.png",
    "summer tilemap-74": "summer tilemap-74.png",
    "summer tilemap-75": "summer tilemap-75.png",
    "summer tilemap-76": "summer tilemap-76.png",
    "summer tilemap-77": "summer tilemap-77.png",
    "summer tilemap-78": "summer tilemap-78.png",
    "summer tilemap-79": "summer tilemap-79.png",
    "summer tilemap-80": "summer tilemap-80.png",
    "summer tilemap-81": "summer tilemap-81.png",
    "summer tilemap-82": "summer tilemap-82.png",
    "summer tilemap-83": "summer tilemap-83.png",
    "summer tilemap-84": "summer tilemap-84.png",
    "summer tilemap-85": "summer tilemap-85.png",
    "summer tilemap-86": "summer tilemap-86.png",
    "summer tilemap-87": "summer tilemap-87.png",
    "summer tilemap-88": "summer tilemap-88.png",
    "summer tilemap-89": "summer tilemap-89.png",
    "summer tilemap-90": "summer tilemap-90.png",
    "summer tilemap-91": "summer tilemap-91.png",
    "summer tilemap-92": "summer tilemap-92.png",
    "summer tilemap-93": "summer tilemap-93.png",
    "summer tilemap-94": "summer tilemap-94.png",
    "summer tilemap-95": "summer tilemap-95.png",
    "summer tilemap-96": "summer tilemap-96.png",
    "summer tilemap-97": "summer tilemap-97.png",
    "summer tilemap-98": "summer tilemap-98.png",
    "summer tilemap-99": "summer tilemap-99.png",
    "summer tilemap-100": "summer tilemap-100.png",
    "summer tilemap-101": "summer tilemap-101.png",
    "summer tilemap-102": "summer tilemap-102.png",
    "summer tilemap-103": "summer tilemap-103.png",
    "summer tilemap-104": "summer tilemap-104.png",
    "summer tilemap-105": "summer tilemap-105.png",
    "summer tilemap-106": "summer tilemap-106.png",
    "summer tilemap-107": "summer tilemap-107.png",
    "summer tilemap-108": "summer tilemap-108.png",
  },
  "winter outside": {
    "winter outside-0": "winter outside-0.png",
    "winter outside-1": "winter outside-1.png",
    "winter outside-2": "winter outside-2.png",
    "winter outside-3": "winter outside-3.png",
    "winter outside-4": "winter outside-4.png",
    "winter outside-5": "winter outside-5.png",
    "winter outside-6": "winter outside-6.png",
    "winter outside-7": "winter outside-7.png",
    "winter outside-8": "winter outside-8.png",
    "winter outside-9": "winter outside-9.png",
    "winter outside-10": "winter outside-10.png",
    "winter outside-11": "winter outside-11.png",
    "winter outside-12": "winter outside-12.png",
    "winter outside-13": "winter outside-13.png",
    "winter outside-14": "winter outside-14.png",
    "winter outside-15": "winter outside-15.png",
    "winter outside-16": "winter outside-16.png",
    "winter outside-17": "winter outside-17.png",
    "winter outside-18": "winter outside-18.png",
    "winter outside-19": "winter outside-19.png",
    "winter outside-20": "winter outside-20.png",
    "winter outside-21": "winter outside-21.png",
    "winter outside-22": "winter outside-22.png",
    "winter outside-23": "winter outside-23.png",
    "winter outside-24": "winter outside-24.png",
    "winter outside-25": "winter outside-25.png",
    "winter outside-26": "winter outside-26.png",
    "winter outside-27": "winter outside-27.png",
    "winter outside-28": "winter outside-28.png",
    "winter outside-29": "winter outside-29.png",
    "winter outside-30": "winter outside-30.png",
    "winter outside-31": "winter outside-31.png",
    "winter outside-32": "winter outside-32.png",
    "winter outside-33": "winter outside-33.png",
    "winter outside-34": "winter outside-34.png",
    "winter outside-35": "winter outside-35.png",
    "winter outside-36": "winter outside-36.png",
    "winter outside-37": "winter outside-37.png",
    "winter outside-38": "winter outside-38.png",
    "winter outside-39": "winter outside-39.png",
    "winter outside-40": "winter outside-40.png",
    "winter outside-41": "winter outside-41.png",
    "winter outside-42": "winter outside-42.png",
    "winter outside-43": "winter outside-43.png",
    "winter outside-44": "winter outside-44.png",
    "winter outside-45": "winter outside-45.png",
    "winter outside-46": "winter outside-46.png",
    "winter outside-47": "winter outside-47.png",
    "winter outside-48": "winter outside-48.png",
    "winter outside-49": "winter outside-49.png",
    "winter outside-50": "winter outside-50.png",
    "winter outside-51": "winter outside-51.png",
    "winter outside-52": "winter outside-52.png",
    "winter outside-53": "winter outside-53.png",
    "winter outside-54": "winter outside-54.png",
    "winter outside-55": "winter outside-55.png",
    "winter outside-56": "winter outside-56.png",
    "winter outside-57": "winter outside-57.png",
    "winter outside-58": "winter outside-58.png",
    "winter outside-59": "winter outside-59.png",
    "winter outside-60": "winter outside-60.png",
    "winter outside-61": "winter outside-61.png",
    "winter outside-62": "winter outside-62.png",
    "winter outside-63": "winter outside-63.png",
    "winter outside-64": "winter outside-64.png",
    "winter outside-65": "winter outside-65.png",
    "winter outside-66": "winter outside-66.png",
    "winter outside-67": "winter outside-67.png",
    "winter outside-68": "winter outside-68.png",
    "winter outside-69": "winter outside-69.png",
    "winter outside-70": "winter outside-70.png",
    "winter outside-71": "winter outside-71.png",
    "winter outside-72": "winter outside-72.png",
    "winter outside-73": "winter outside-73.png",
    "winter outside-74": "winter outside-74.png",
    "winter outside-75": "winter outside-75.png",
    "winter outside-76": "winter outside-76.png",
    "winter outside-77": "winter outside-77.png",
    "winter outside-78": "winter outside-78.png",
    "winter outside-79": "winter outside-79.png",
    "winter outside-80": "winter outside-80.png",
    "winter outside-81": "winter outside-81.png",
    "winter outside-82": "winter outside-82.png",
    "winter outside-83": "winter outside-83.png",
    "winter outside-84": "winter outside-84.png",
    "winter outside-85": "winter outside-85.png",
    "winter outside-86": "winter outside-86.png",
    "winter outside-87": "winter outside-87.png",
    "winter outside-88": "winter outside-88.png",
    "winter outside-89": "winter outside-89.png",
    "winter outside-90": "winter outside-90.png",
    "winter outside-91": "winter outside-91.png",
    "winter outside-92": "winter outside-92.png",
    "winter outside-93": "winter outside-93.png",
    "winter outside-94": "winter outside-94.png",
    "winter outside-95": "winter outside-95.png",
    "winter outside-96": "winter outside-96.png",
    "winter outside-97": "winter outside-97.png",
    "winter outside-98": "winter outside-98.png",
    "winter outside-99": "winter outside-99.png",
    "winter outside-100": "winter outside-100.png",
    "winter outside-101": "winter outside-101.png",
    "winter outside-102": "winter outside-102.png",
    "winter outside-103": "winter outside-103.png",
    "winter outside-104": "winter outside-104.png",
    "winter outside-105": "winter outside-105.png",
    "winter outside-106": "winter outside-106.png",
    "winter outside-107": "winter outside-107.png",
    "winter outside-108": "winter outside-108.png",
    "winter outside-109": "winter outside-109.png",
    "winter outside-110": "winter outside-110.png",
    "winter outside-111": "winter outside-111.png",
    "winter outside-112": "winter outside-112.png",
    "winter outside-113": "winter outside-113.png",
    "winter outside-114": "winter outside-114.png",
  },
};
