export const wonderSpriteSheetMap = {
  'cat kigurumi walk and idle': {
    'cat kigurumi walk and idle-0': 'cat kigurumi walk and idle-0.png',
    'cat kigurumi walk and idle-1': 'cat kigurumi walk and idle-1.png',
    'cat kigurumi walk and idle-2': 'cat kigurumi walk and idle-2.png',
    'cat kigurumi walk and idle-3': 'cat kigurumi walk and idle-3.png',
    'cat kigurumi walk and idle-4': 'cat kigurumi walk and idle-4.png',
    'cat kigurumi walk and idle-5': 'cat kigurumi walk and idle-5.png',
    'cat kigurumi walk and idle-6': 'cat kigurumi walk and idle-6.png',
    'cat kigurumi walk and idle-7': 'cat kigurumi walk and idle-7.png',
    'cat kigurumi walk and idle-8': 'cat kigurumi walk and idle-8.png',
    'cat kigurumi walk and idle-9': 'cat kigurumi walk and idle-9.png',
    'cat kigurumi walk and idle-10': 'cat kigurumi walk and idle-10.png',
    'cat kigurumi walk and idle-11': 'cat kigurumi walk and idle-11.png',
    'cat kigurumi walk and idle-12': 'cat kigurumi walk and idle-12.png',
    'cat kigurumi walk and idle-13': 'cat kigurumi walk and idle-13.png',
    'cat kigurumi walk and idle-14': 'cat kigurumi walk and idle-14.png',
    'cat kigurumi walk and idle-15': 'cat kigurumi walk and idle-15.png',
    'cat kigurumi walk and idle-16': 'cat kigurumi walk and idle-16.png',
    'cat kigurumi walk and idle-17': 'cat kigurumi walk and idle-17.png',
    'cat kigurumi walk and idle-18': 'cat kigurumi walk and idle-18.png',
    'cat kigurumi walk and idle-19': 'cat kigurumi walk and idle-19.png',
  },
  'walk and idle': {
    'walk and idle-0': 'walk and idle-0.png',
    'walk and idle-1': 'walk and idle-1.png',
    'walk and idle-2': 'walk and idle-2.png',
    'walk and idle-3': 'walk and idle-3.png',
    'walk and idle-4': 'walk and idle-4.png',
    'walk and idle-5': 'walk and idle-5.png',
    'walk and idle-6': 'walk and idle-6.png',
    'walk and idle-7': 'walk and idle-7.png',
    'walk and idle-8': 'walk and idle-8.png',
    'walk and idle-9': 'walk and idle-9.png',
    'walk and idle-10': 'walk and idle-10.png',
    'walk and idle-11': 'walk and idle-11.png',
    'walk and idle-12': 'walk and idle-12.png',
    'walk and idle-13': 'walk and idle-13.png',
    'walk and idle-14': 'walk and idle-14.png',
    'walk and idle-15': 'walk and idle-15.png',
    'walk and idle-16': 'walk and idle-16.png',
    'walk and idle-17': 'walk and idle-17.png',
    'walk and idle-18': 'walk and idle-18.png',
    'walk and idle-19': 'walk and idle-19.png',
  },
};
