export const BLOCK_SIZE = 16;
export const MAP_ROW = 15;
export const MAP_COL = 15;
export const MAP_HEIGHT = MAP_ROW * BLOCK_SIZE;
export const MAP_WIDTH = MAP_COL * BLOCK_SIZE;
export const KIGURUMI_SPRITE_SHEET = "/wonderGame/kigurumi.png";
export const KIGURUMI_SPRITE_SHEET_JSON = "/wonderGame/kigurumi.json";
export const TILEMAP_SPRITE_SHEET = "/wonderGame/tilemap.png";
export const TILEMAP_SPRITE_SHEET_JSON = "/wonderGame/tilemap.json";
