export const spriteSheet = {
  "attack and die": {
    "attack and die-0": "attack and die-0.png",
    "attack and die-1": "attack and die-1.png",
    "attack and die-2": "attack and die-2.png",
    "attack and die-3": "attack and die-3.png",
    "attack and die-4": "attack and die-4.png",
    "attack and die-5": "attack and die-5.png",
    "attack and die-6": "attack and die-6.png",
    "attack and die-7": "attack and die-7.png",
    "attack and die-8": "attack and die-8.png",
    "attack and die-9": "attack and die-9.png",
    "attack and die-10": "attack and die-10.png",
    "attack and die-11": "attack and die-11.png",
    "attack and die-12": "attack and die-12.png",
    "attack and die-13": "attack and die-13.png",
    "attack and die-14": "attack and die-14.png",
    "attack and die-15": "attack and die-15.png",
    "attack and die-16": "attack and die-16.png",
    "attack and die-17": "attack and die-17.png",
  },
  "autumn items": {
    "autumn items-0": "autumn items-0.png",
    "autumn items-1": "autumn items-1.png",
    "autumn items-2": "autumn items-2.png",
    "autumn items-3": "autumn items-3.png",
    "autumn items-4": "autumn items-4.png",
    "autumn items-5": "autumn items-5.png",
    "autumn items-6": "autumn items-6.png",
    "autumn items-7": "autumn items-7.png",
    "autumn items-8": "autumn items-8.png",
    "autumn items-9": "autumn items-9.png",
    "autumn items-10": "autumn items-10.png",
    "autumn items-11": "autumn items-11.png",
    "autumn items-12": "autumn items-12.png",
    "autumn items-13": "autumn items-13.png",
    "autumn items-14": "autumn items-14.png",
    "autumn items-15": "autumn items-15.png",
    "autumn items-16": "autumn items-16.png",
    "autumn items-17": "autumn items-17.png",
    "autumn items-18": "autumn items-18.png",
    "autumn items-19": "autumn items-19.png",
    "autumn items-20": "autumn items-20.png",
    "autumn items-21": "autumn items-21.png",
    "autumn items-22": "autumn items-22.png",
    "autumn items-23": "autumn items-23.png",
    "autumn items-24": "autumn items-24.png",
    "autumn items-25": "autumn items-25.png",
    "autumn items-26": "autumn items-26.png",
    "autumn items-27": "autumn items-27.png",
    "autumn items-28": "autumn items-28.png",
    "autumn items-29": "autumn items-29.png",
    "autumn items-30": "autumn items-30.png",
    "autumn items-31": "autumn items-31.png",
    "autumn items-32": "autumn items-32.png",
    "autumn items-33": "autumn items-33.png",
    "autumn items-34": "autumn items-34.png",
    "autumn items-35": "autumn items-35.png",
    "autumn items-36": "autumn items-36.png",
    "autumn items-37": "autumn items-37.png",
    "autumn items-38": "autumn items-38.png",
    "autumn items-39": "autumn items-39.png",
    "autumn items-40": "autumn items-40.png",
    "autumn items-41": "autumn items-41.png",
    "autumn items-42": "autumn items-42.png",
    "autumn items-43": "autumn items-43.png",
    "autumn items-44": "autumn items-44.png",
    "autumn items-45": "autumn items-45.png",
    "autumn items-46": "autumn items-46.png",
    "autumn items-47": "autumn items-47.png",
    "autumn items-48": "autumn items-48.png",
    "autumn items-49": "autumn items-49.png",
    "autumn items-50": "autumn items-50.png",
    "autumn items-51": "autumn items-51.png",
    "autumn items-52": "autumn items-52.png",
    "autumn items-53": "autumn items-53.png",
    "autumn items-54": "autumn items-54.png",
    "autumn items-55": "autumn items-55.png",
    "autumn items-56": "autumn items-56.png",
    "autumn items-57": "autumn items-57.png",
    "autumn items-58": "autumn items-58.png",
    "autumn items-59": "autumn items-59.png",
    "autumn items-60": "autumn items-60.png",
    "autumn items-61": "autumn items-61.png",
    "autumn items-62": "autumn items-62.png",
    "autumn items-63": "autumn items-63.png",
    "autumn items-64": "autumn items-64.png",
    "autumn items-65": "autumn items-65.png",
    "autumn items-66": "autumn items-66.png",
    "autumn items-67": "autumn items-67.png",
    "autumn items-68": "autumn items-68.png",
    "autumn items-69": "autumn items-69.png",
    "autumn items-70": "autumn items-70.png",
    "autumn items-71": "autumn items-71.png",
    "autumn items-72": "autumn items-72.png",
  },
  "autumn tilemap": {
    "autumn tilemap-0": "autumn tilemap-0.png",
    "autumn tilemap-1": "autumn tilemap-1.png",
    "autumn tilemap-2": "autumn tilemap-2.png",
    "autumn tilemap-3": "autumn tilemap-3.png",
    "autumn tilemap-4": "autumn tilemap-4.png",
    "autumn tilemap-5": "autumn tilemap-5.png",
    "autumn tilemap-6": "autumn tilemap-6.png",
    "autumn tilemap-7": "autumn tilemap-7.png",
    "autumn tilemap-8": "autumn tilemap-8.png",
    "autumn tilemap-9": "autumn tilemap-9.png",
    "autumn tilemap-10": "autumn tilemap-10.png",
    "autumn tilemap-11": "autumn tilemap-11.png",
    "autumn tilemap-12": "autumn tilemap-12.png",
    "autumn tilemap-13": "autumn tilemap-13.png",
    "autumn tilemap-14": "autumn tilemap-14.png",
    "autumn tilemap-15": "autumn tilemap-15.png",
    "autumn tilemap-16": "autumn tilemap-16.png",
    "autumn tilemap-17": "autumn tilemap-17.png",
    "autumn tilemap-18": "autumn tilemap-18.png",
    "autumn tilemap-19": "autumn tilemap-19.png",
    "autumn tilemap-20": "autumn tilemap-20.png",
    "autumn tilemap-21": "autumn tilemap-21.png",
    "autumn tilemap-22": "autumn tilemap-22.png",
    "autumn tilemap-23": "autumn tilemap-23.png",
    "autumn tilemap-24": "autumn tilemap-24.png",
    "autumn tilemap-25": "autumn tilemap-25.png",
    "autumn tilemap-26": "autumn tilemap-26.png",
    "autumn tilemap-27": "autumn tilemap-27.png",
    "autumn tilemap-28": "autumn tilemap-28.png",
    "autumn tilemap-29": "autumn tilemap-29.png",
    "autumn tilemap-30": "autumn tilemap-30.png",
    "autumn tilemap-31": "autumn tilemap-31.png",
    "autumn tilemap-32": "autumn tilemap-32.png",
    "autumn tilemap-33": "autumn tilemap-33.png",
    "autumn tilemap-34": "autumn tilemap-34.png",
    "autumn tilemap-35": "autumn tilemap-35.png",
    "autumn tilemap-36": "autumn tilemap-36.png",
    "autumn tilemap-37": "autumn tilemap-37.png",
    "autumn tilemap-38": "autumn tilemap-38.png",
    "autumn tilemap-39": "autumn tilemap-39.png",
    "autumn tilemap-40": "autumn tilemap-40.png",
    "autumn tilemap-41": "autumn tilemap-41.png",
    "autumn tilemap-42": "autumn tilemap-42.png",
    "autumn tilemap-43": "autumn tilemap-43.png",
    "autumn tilemap-44": "autumn tilemap-44.png",
    "autumn tilemap-45": "autumn tilemap-45.png",
    "autumn tilemap-46": "autumn tilemap-46.png",
    "autumn tilemap-47": "autumn tilemap-47.png",
    "autumn tilemap-48": "autumn tilemap-48.png",
    "autumn tilemap-49": "autumn tilemap-49.png",
    "autumn tilemap-50": "autumn tilemap-50.png",
    "autumn tilemap-51": "autumn tilemap-51.png",
    "autumn tilemap-52": "autumn tilemap-52.png",
    "autumn tilemap-53": "autumn tilemap-53.png",
    "autumn tilemap-54": "autumn tilemap-54.png",
    "autumn tilemap-55": "autumn tilemap-55.png",
    "autumn tilemap-56": "autumn tilemap-56.png",
    "autumn tilemap-57": "autumn tilemap-57.png",
    "autumn tilemap-58": "autumn tilemap-58.png",
    "autumn tilemap-59": "autumn tilemap-59.png",
    "autumn tilemap-60": "autumn tilemap-60.png",
    "autumn tilemap-61": "autumn tilemap-61.png",
    "autumn tilemap-62": "autumn tilemap-62.png",
    "autumn tilemap-63": "autumn tilemap-63.png",
    "autumn tilemap-64": "autumn tilemap-64.png",
    "autumn tilemap-65": "autumn tilemap-65.png",
    "autumn tilemap-66": "autumn tilemap-66.png",
    "autumn tilemap-67": "autumn tilemap-67.png",
    "autumn tilemap-68": "autumn tilemap-68.png",
    "autumn tilemap-69": "autumn tilemap-69.png",
    "autumn tilemap-70": "autumn tilemap-70.png",
    "autumn tilemap-71": "autumn tilemap-71.png",
    "autumn tilemap-72": "autumn tilemap-72.png",
    "autumn tilemap-73": "autumn tilemap-73.png",
    "autumn tilemap-74": "autumn tilemap-74.png",
    "autumn tilemap-75": "autumn tilemap-75.png",
    "autumn tilemap-76": "autumn tilemap-76.png",
    "autumn tilemap-77": "autumn tilemap-77.png",
    "autumn tilemap-78": "autumn tilemap-78.png",
    "autumn tilemap-79": "autumn tilemap-79.png",
    "autumn tilemap-80": "autumn tilemap-80.png",
    "autumn tilemap-81": "autumn tilemap-81.png",
    "autumn tilemap-82": "autumn tilemap-82.png",
    "autumn tilemap-83": "autumn tilemap-83.png",
    "autumn tilemap-84": "autumn tilemap-84.png",
    "autumn tilemap-85": "autumn tilemap-85.png",
    "autumn tilemap-86": "autumn tilemap-86.png",
    "autumn tilemap-87": "autumn tilemap-87.png",
    "autumn tilemap-88": "autumn tilemap-88.png",
    "autumn tilemap-89": "autumn tilemap-89.png",
    "autumn tilemap-90": "autumn tilemap-90.png",
    "autumn tilemap-91": "autumn tilemap-91.png",
    "autumn tilemap-92": "autumn tilemap-92.png",
    "autumn tilemap-93": "autumn tilemap-93.png",
    "autumn tilemap-94": "autumn tilemap-94.png",
    "autumn tilemap-95": "autumn tilemap-95.png",
    "autumn tilemap-96": "autumn tilemap-96.png",
    "autumn tilemap-97": "autumn tilemap-97.png",
    "autumn tilemap-98": "autumn tilemap-98.png",
    "autumn tilemap-99": "autumn tilemap-99.png",
    "autumn tilemap-100": "autumn tilemap-100.png",
    "autumn tilemap-101": "autumn tilemap-101.png",
    "autumn tilemap-102": "autumn tilemap-102.png",
    "autumn tilemap-103": "autumn tilemap-103.png",
    "autumn tilemap-104": "autumn tilemap-104.png",
    "autumn tilemap-105": "autumn tilemap-105.png",
    "autumn tilemap-106": "autumn tilemap-106.png",
    "autumn tilemap-107": "autumn tilemap-107.png",
    "autumn tilemap-108": "autumn tilemap-108.png",
  },
  "blue mushroom sheet": {
    "blue mushroom sheet-0": "blue mushroom sheet-0.png",
    "blue mushroom sheet-1": "blue mushroom sheet-1.png",
    "blue mushroom sheet-2": "blue mushroom sheet-2.png",
    "blue mushroom sheet-3": "blue mushroom sheet-3.png",
    "blue mushroom sheet-4": "blue mushroom sheet-4.png",
    "blue mushroom sheet-5": "blue mushroom sheet-5.png",
    "blue mushroom sheet-6": "blue mushroom sheet-6.png",
    "blue mushroom sheet-7": "blue mushroom sheet-7.png",
    "blue mushroom sheet-8": "blue mushroom sheet-8.png",
    "blue mushroom sheet-9": "blue mushroom sheet-9.png",
    "blue mushroom sheet-10": "blue mushroom sheet-10.png",
    "blue mushroom sheet-11": "blue mushroom sheet-11.png",
    "blue mushroom sheet-12": "blue mushroom sheet-12.png",
    "blue mushroom sheet-13": "blue mushroom sheet-13.png",
    "blue mushroom sheet-14": "blue mushroom sheet-14.png",
    "blue mushroom sheet-15": "blue mushroom sheet-15.png",
    "blue mushroom sheet-16": "blue mushroom sheet-16.png",
    "blue mushroom sheet-17": "blue mushroom sheet-17.png",
    "blue mushroom sheet-18": "blue mushroom sheet-18.png",
    "blue mushroom sheet-19": "blue mushroom sheet-19.png",
    "blue mushroom sheet-20": "blue mushroom sheet-20.png",
    "blue mushroom sheet-21": "blue mushroom sheet-21.png",
    "blue mushroom sheet-22": "blue mushroom sheet-22.png",
    "blue mushroom sheet-23": "blue mushroom sheet-23.png",
    "blue mushroom sheet-24": "blue mushroom sheet-24.png",
    "blue mushroom sheet-25": "blue mushroom sheet-25.png",
    "blue mushroom sheet-26": "blue mushroom sheet-26.png",
    "blue mushroom sheet-27": "blue mushroom sheet-27.png",
    "blue mushroom sheet-28": "blue mushroom sheet-28.png",
    "blue mushroom sheet-29": "blue mushroom sheet-29.png",
    "blue mushroom sheet-30": "blue mushroom sheet-30.png",
    "blue mushroom sheet-31": "blue mushroom sheet-31.png",
    "blue mushroom sheet-32": "blue mushroom sheet-32.png",
    "blue mushroom sheet-33": "blue mushroom sheet-33.png",
    "blue mushroom sheet-34": "blue mushroom sheet-34.png",
    "blue mushroom sheet-35": "blue mushroom sheet-35.png",
    "blue mushroom sheet-36": "blue mushroom sheet-36.png",
    "blue mushroom sheet-37": "blue mushroom sheet-37.png",
    "blue mushroom sheet-38": "blue mushroom sheet-38.png",
    "blue mushroom sheet-39": "blue mushroom sheet-39.png",
    "blue mushroom sheet-40": "blue mushroom sheet-40.png",
    "blue mushroom sheet-41": "blue mushroom sheet-41.png",
    "blue mushroom sheet-42": "blue mushroom sheet-42.png",
    "blue mushroom sheet-43": "blue mushroom sheet-43.png",
    "blue mushroom sheet-44": "blue mushroom sheet-44.png",
    "blue mushroom sheet-45": "blue mushroom sheet-45.png",
    "blue mushroom sheet-46": "blue mushroom sheet-46.png",
    "blue mushroom sheet-47": "blue mushroom sheet-47.png",
    "blue mushroom sheet-48": "blue mushroom sheet-48.png",
    "blue mushroom sheet-49": "blue mushroom sheet-49.png",
    "blue mushroom sheet-50": "blue mushroom sheet-50.png",
    "blue mushroom sheet-51": "blue mushroom sheet-51.png",
  },
  "brown mushroom sheet": {
    "brown mushroom sheet-0": "brown mushroom sheet-0.png",
    "brown mushroom sheet-1": "brown mushroom sheet-1.png",
    "brown mushroom sheet-2": "brown mushroom sheet-2.png",
    "brown mushroom sheet-3": "brown mushroom sheet-3.png",
    "brown mushroom sheet-4": "brown mushroom sheet-4.png",
    "brown mushroom sheet-5": "brown mushroom sheet-5.png",
    "brown mushroom sheet-6": "brown mushroom sheet-6.png",
    "brown mushroom sheet-7": "brown mushroom sheet-7.png",
    "brown mushroom sheet-8": "brown mushroom sheet-8.png",
    "brown mushroom sheet-9": "brown mushroom sheet-9.png",
    "brown mushroom sheet-10": "brown mushroom sheet-10.png",
    "brown mushroom sheet-11": "brown mushroom sheet-11.png",
    "brown mushroom sheet-12": "brown mushroom sheet-12.png",
    "brown mushroom sheet-13": "brown mushroom sheet-13.png",
    "brown mushroom sheet-14": "brown mushroom sheet-14.png",
    "brown mushroom sheet-15": "brown mushroom sheet-15.png",
    "brown mushroom sheet-16": "brown mushroom sheet-16.png",
    "brown mushroom sheet-17": "brown mushroom sheet-17.png",
    "brown mushroom sheet-18": "brown mushroom sheet-18.png",
    "brown mushroom sheet-19": "brown mushroom sheet-19.png",
    "brown mushroom sheet-20": "brown mushroom sheet-20.png",
    "brown mushroom sheet-21": "brown mushroom sheet-21.png",
    "brown mushroom sheet-22": "brown mushroom sheet-22.png",
    "brown mushroom sheet-23": "brown mushroom sheet-23.png",
    "brown mushroom sheet-24": "brown mushroom sheet-24.png",
    "brown mushroom sheet-25": "brown mushroom sheet-25.png",
    "brown mushroom sheet-26": "brown mushroom sheet-26.png",
    "brown mushroom sheet-27": "brown mushroom sheet-27.png",
    "brown mushroom sheet-28": "brown mushroom sheet-28.png",
    "brown mushroom sheet-29": "brown mushroom sheet-29.png",
    "brown mushroom sheet-30": "brown mushroom sheet-30.png",
    "brown mushroom sheet-31": "brown mushroom sheet-31.png",
    "brown mushroom sheet-32": "brown mushroom sheet-32.png",
    "brown mushroom sheet-33": "brown mushroom sheet-33.png",
    "brown mushroom sheet-34": "brown mushroom sheet-34.png",
    "brown mushroom sheet-35": "brown mushroom sheet-35.png",
    "brown mushroom sheet-36": "brown mushroom sheet-36.png",
    "brown mushroom sheet-37": "brown mushroom sheet-37.png",
    "brown mushroom sheet-38": "brown mushroom sheet-38.png",
    "brown mushroom sheet-39": "brown mushroom sheet-39.png",
    "brown mushroom sheet-40": "brown mushroom sheet-40.png",
    "brown mushroom sheet-41": "brown mushroom sheet-41.png",
    "brown mushroom sheet-42": "brown mushroom sheet-42.png",
    "brown mushroom sheet-43": "brown mushroom sheet-43.png",
    "brown mushroom sheet-44": "brown mushroom sheet-44.png",
    "brown mushroom sheet-45": "brown mushroom sheet-45.png",
    "brown mushroom sheet-46": "brown mushroom sheet-46.png",
    "brown mushroom sheet-47": "brown mushroom sheet-47.png",
    "brown mushroom sheet-48": "brown mushroom sheet-48.png",
    "brown mushroom sheet-49": "brown mushroom sheet-49.png",
    "brown mushroom sheet-50": "brown mushroom sheet-50.png",
    "brown mushroom sheet-51": "brown mushroom sheet-51.png",
  },
  "cat kigurumi attack and die": {
    "cat kigurumi attack and die-0": "cat kigurumi attack and die-0.png",
    "cat kigurumi attack and die-1": "cat kigurumi attack and die-1.png",
    "cat kigurumi attack and die-2": "cat kigurumi attack and die-2.png",
    "cat kigurumi attack and die-3": "cat kigurumi attack and die-3.png",
    "cat kigurumi attack and die-4": "cat kigurumi attack and die-4.png",
    "cat kigurumi attack and die-5": "cat kigurumi attack and die-5.png",
    "cat kigurumi attack and die-6": "cat kigurumi attack and die-6.png",
    "cat kigurumi attack and die-7": "cat kigurumi attack and die-7.png",
    "cat kigurumi attack and die-8": "cat kigurumi attack and die-8.png",
    "cat kigurumi attack and die-9": "cat kigurumi attack and die-9.png",
    "cat kigurumi attack and die-10": "cat kigurumi attack and die-10.png",
    "cat kigurumi attack and die-11": "cat kigurumi attack and die-11.png",
    "cat kigurumi attack and die-12": "cat kigurumi attack and die-12.png",
    "cat kigurumi attack and die-13": "cat kigurumi attack and die-13.png",
    "cat kigurumi attack and die-14": "cat kigurumi attack and die-14.png",
    "cat kigurumi attack and die-15": "cat kigurumi attack and die-15.png",
    "cat kigurumi attack and die-16": "cat kigurumi attack and die-16.png",
    "cat kigurumi attack and die-17": "cat kigurumi attack and die-17.png",
  },
  "cat kigurumi walk and idle": {
    "cat kigurumi walk and idle-0": "cat kigurumi walk and idle-0.png",
    "cat kigurumi walk and idle-1": "cat kigurumi walk and idle-1.png",
    "cat kigurumi walk and idle-2": "cat kigurumi walk and idle-2.png",
    "cat kigurumi walk and idle-3": "cat kigurumi walk and idle-3.png",
    "cat kigurumi walk and idle-4": "cat kigurumi walk and idle-4.png",
    "cat kigurumi walk and idle-5": "cat kigurumi walk and idle-5.png",
    "cat kigurumi walk and idle-6": "cat kigurumi walk and idle-6.png",
    "cat kigurumi walk and idle-7": "cat kigurumi walk and idle-7.png",
    "cat kigurumi walk and idle-8": "cat kigurumi walk and idle-8.png",
    "cat kigurumi walk and idle-9": "cat kigurumi walk and idle-9.png",
    "cat kigurumi walk and idle-10": "cat kigurumi walk and idle-10.png",
    "cat kigurumi walk and idle-11": "cat kigurumi walk and idle-11.png",
    "cat kigurumi walk and idle-12": "cat kigurumi walk and idle-12.png",
    "cat kigurumi walk and idle-13": "cat kigurumi walk and idle-13.png",
    "cat kigurumi walk and idle-14": "cat kigurumi walk and idle-14.png",
    "cat kigurumi walk and idle-15": "cat kigurumi walk and idle-15.png",
    "cat kigurumi walk and idle-16": "cat kigurumi walk and idle-16.png",
    "cat kigurumi walk and idle-17": "cat kigurumi walk and idle-17.png",
    "cat kigurumi walk and idle-18": "cat kigurumi walk and idle-18.png",
    "cat kigurumi walk and idle-19": "cat kigurumi walk and idle-19.png",
  },
  furniture: {
    "furniture-0": "furniture-0.png",
    "furniture-1": "furniture-1.png",
    "furniture-2": "furniture-2.png",
    "furniture-3": "furniture-3.png",
    "furniture-4": "furniture-4.png",
    "furniture-5": "furniture-5.png",
    "furniture-6": "furniture-6.png",
    "furniture-7": "furniture-7.png",
    "furniture-8": "furniture-8.png",
    "furniture-9": "furniture-9.png",
    "furniture-10": "furniture-10.png",
    "furniture-11": "furniture-11.png",
    "furniture-12": "furniture-12.png",
    "furniture-13": "furniture-13.png",
    "furniture-14": "furniture-14.png",
    "furniture-15": "furniture-15.png",
    "furniture-16": "furniture-16.png",
    "furniture-17": "furniture-17.png",
    "furniture-18": "furniture-18.png",
    "furniture-19": "furniture-19.png",
    "furniture-20": "furniture-20.png",
    "furniture-21": "furniture-21.png",
    "furniture-22": "furniture-22.png",
    "furniture-23": "furniture-23.png",
    "furniture-24": "furniture-24.png",
    "furniture-25": "furniture-25.png",
    "furniture-26": "furniture-26.png",
    "furniture-27": "furniture-27.png",
    "furniture-28": "furniture-28.png",
    "furniture-29": "furniture-29.png",
    "furniture-30": "furniture-30.png",
    "furniture-31": "furniture-31.png",
    "furniture-32": "furniture-32.png",
    "furniture-33": "furniture-33.png",
    "furniture-34": "furniture-34.png",
    "furniture-35": "furniture-35.png",
    "furniture-36": "furniture-36.png",
    "furniture-37": "furniture-37.png",
    "furniture-38": "furniture-38.png",
    "furniture-39": "furniture-39.png",
    "furniture-40": "furniture-40.png",
    "furniture-41": "furniture-41.png",
    "furniture-42": "furniture-42.png",
    "furniture-43": "furniture-43.png",
    "furniture-44": "furniture-44.png",
    "furniture-45": "furniture-45.png",
    "furniture-46": "furniture-46.png",
    "furniture-47": "furniture-47.png",
    "furniture-48": "furniture-48.png",
    "furniture-49": "furniture-49.png",
    "furniture-50": "furniture-50.png",
    "furniture-51": "furniture-51.png",
    "furniture-52": "furniture-52.png",
    "furniture-53": "furniture-53.png",
    "furniture-54": "furniture-54.png",
    "furniture-55": "furniture-55.png",
    "furniture-56": "furniture-56.png",
    "furniture-57": "furniture-57.png",
    "furniture-58": "furniture-58.png",
    "furniture-59": "furniture-59.png",
    "furniture-60": "furniture-60.png",
    "furniture-61": "furniture-61.png",
  },
  inside: {
    "inside-0": "inside-0.png",
    "inside-1": "inside-1.png",
    "inside-2": "inside-2.png",
    "inside-3": "inside-3.png",
    "inside-4": "inside-4.png",
    "inside-5": "inside-5.png",
    "inside-6": "inside-6.png",
    "inside-7": "inside-7.png",
    "inside-8": "inside-8.png",
    "inside-9": "inside-9.png",
    "inside-10": "inside-10.png",
    "inside-11": "inside-11.png",
    "inside-12": "inside-12.png",
    "inside-13": "inside-13.png",
    "inside-14": "inside-14.png",
    "inside-15": "inside-15.png",
    "inside-16": "inside-16.png",
    "inside-17": "inside-17.png",
    "inside-18": "inside-18.png",
    "inside-19": "inside-19.png",
    "inside-20": "inside-20.png",
    "inside-21": "inside-21.png",
    "inside-22": "inside-22.png",
    "inside-23": "inside-23.png",
    "inside-24": "inside-24.png",
    "inside-25": "inside-25.png",
    "inside-26": "inside-26.png",
    "inside-27": "inside-27.png",
    "inside-28": "inside-28.png",
    "inside-29": "inside-29.png",
    "inside-30": "inside-30.png",
    "inside-31": "inside-31.png",
    "inside-32": "inside-32.png",
    "inside-33": "inside-33.png",
    "inside-34": "inside-34.png",
    "inside-35": "inside-35.png",
    "inside-36": "inside-36.png",
    "inside-37": "inside-37.png",
    "inside-38": "inside-38.png",
    "inside-39": "inside-39.png",
    "inside-40": "inside-40.png",
    "inside-41": "inside-41.png",
    "inside-42": "inside-42.png",
    "inside-43": "inside-43.png",
    "inside-44": "inside-44.png",
    "inside-45": "inside-45.png",
    "inside-46": "inside-46.png",
    "inside-47": "inside-47.png",
    "inside-48": "inside-48.png",
    "inside-49": "inside-49.png",
    "inside-50": "inside-50.png",
  },
  objects: {
    "objects-0": "objects-0.png",
    "objects-1": "objects-1.png",
    "objects-2": "objects-2.png",
    "objects-3": "objects-3.png",
    "objects-4": "objects-4.png",
    "objects-5": "objects-5.png",
    "objects-6": "objects-6.png",
    "objects-7": "objects-7.png",
    "objects-8": "objects-8.png",
    "objects-9": "objects-9.png",
    "objects-10": "objects-10.png",
    "objects-11": "objects-11.png",
    "objects-12": "objects-12.png",
    "objects-13": "objects-13.png",
    "objects-14": "objects-14.png",
    "objects-15": "objects-15.png",
    "objects-16": "objects-16.png",
    "objects-17": "objects-17.png",
    "objects-18": "objects-18.png",
  },
  "spring tilemap": {
    "spring tilemap-0": "spring tilemap-0.png",
    "spring tilemap-1": "spring tilemap-1.png",
    "spring tilemap-2": "spring tilemap-2.png",
    "spring tilemap-3": "spring tilemap-3.png",
    "spring tilemap-4": "spring tilemap-4.png",
    "spring tilemap-5": "spring tilemap-5.png",
    "spring tilemap-6": "spring tilemap-6.png",
    "spring tilemap-7": "spring tilemap-7.png",
    "spring tilemap-8": "spring tilemap-8.png",
    "spring tilemap-9": "spring tilemap-9.png",
    "spring tilemap-10": "spring tilemap-10.png",
    "spring tilemap-11": "spring tilemap-11.png",
    "spring tilemap-12": "spring tilemap-12.png",
    "spring tilemap-13": "spring tilemap-13.png",
    "spring tilemap-14": "spring tilemap-14.png",
    "spring tilemap-15": "spring tilemap-15.png",
    "spring tilemap-16": "spring tilemap-16.png",
    "spring tilemap-17": "spring tilemap-17.png",
    "spring tilemap-18": "spring tilemap-18.png",
    "spring tilemap-19": "spring tilemap-19.png",
    "spring tilemap-20": "spring tilemap-20.png",
    "spring tilemap-21": "spring tilemap-21.png",
    "spring tilemap-22": "spring tilemap-22.png",
    "spring tilemap-23": "spring tilemap-23.png",
    "spring tilemap-24": "spring tilemap-24.png",
    "spring tilemap-25": "spring tilemap-25.png",
    "spring tilemap-26": "spring tilemap-26.png",
    "spring tilemap-27": "spring tilemap-27.png",
    "spring tilemap-28": "spring tilemap-28.png",
    "spring tilemap-29": "spring tilemap-29.png",
    "spring tilemap-30": "spring tilemap-30.png",
    "spring tilemap-31": "spring tilemap-31.png",
    "spring tilemap-32": "spring tilemap-32.png",
    "spring tilemap-33": "spring tilemap-33.png",
    "spring tilemap-34": "spring tilemap-34.png",
    "spring tilemap-35": "spring tilemap-35.png",
    "spring tilemap-36": "spring tilemap-36.png",
    "spring tilemap-37": "spring tilemap-37.png",
    "spring tilemap-38": "spring tilemap-38.png",
    "spring tilemap-39": "spring tilemap-39.png",
    "spring tilemap-40": "spring tilemap-40.png",
    "spring tilemap-41": "spring tilemap-41.png",
    "spring tilemap-42": "spring tilemap-42.png",
    "spring tilemap-43": "spring tilemap-43.png",
    "spring tilemap-44": "spring tilemap-44.png",
    "spring tilemap-45": "spring tilemap-45.png",
    "spring tilemap-46": "spring tilemap-46.png",
    "spring tilemap-47": "spring tilemap-47.png",
    "spring tilemap-48": "spring tilemap-48.png",
    "spring tilemap-49": "spring tilemap-49.png",
    "spring tilemap-50": "spring tilemap-50.png",
    "spring tilemap-51": "spring tilemap-51.png",
    "spring tilemap-52": "spring tilemap-52.png",
    "spring tilemap-53": "spring tilemap-53.png",
    "spring tilemap-54": "spring tilemap-54.png",
    "spring tilemap-55": "spring tilemap-55.png",
    "spring tilemap-56": "spring tilemap-56.png",
    "spring tilemap-57": "spring tilemap-57.png",
    "spring tilemap-58": "spring tilemap-58.png",
    "spring tilemap-59": "spring tilemap-59.png",
    "spring tilemap-60": "spring tilemap-60.png",
    "spring tilemap-61": "spring tilemap-61.png",
    "spring tilemap-62": "spring tilemap-62.png",
    "spring tilemap-63": "spring tilemap-63.png",
    "spring tilemap-64": "spring tilemap-64.png",
    "spring tilemap-65": "spring tilemap-65.png",
    "spring tilemap-66": "spring tilemap-66.png",
    "spring tilemap-67": "spring tilemap-67.png",
    "spring tilemap-68": "spring tilemap-68.png",
    "spring tilemap-69": "spring tilemap-69.png",
    "spring tilemap-70": "spring tilemap-70.png",
    "spring tilemap-71": "spring tilemap-71.png",
    "spring tilemap-72": "spring tilemap-72.png",
    "spring tilemap-73": "spring tilemap-73.png",
    "spring tilemap-74": "spring tilemap-74.png",
    "spring tilemap-75": "spring tilemap-75.png",
    "spring tilemap-76": "spring tilemap-76.png",
    "spring tilemap-77": "spring tilemap-77.png",
    "spring tilemap-78": "spring tilemap-78.png",
    "spring tilemap-79": "spring tilemap-79.png",
    "spring tilemap-80": "spring tilemap-80.png",
    "spring tilemap-81": "spring tilemap-81.png",
    "spring tilemap-82": "spring tilemap-82.png",
    "spring tilemap-83": "spring tilemap-83.png",
    "spring tilemap-84": "spring tilemap-84.png",
    "spring tilemap-85": "spring tilemap-85.png",
    "spring tilemap-86": "spring tilemap-86.png",
    "spring tilemap-87": "spring tilemap-87.png",
    "spring tilemap-88": "spring tilemap-88.png",
    "spring tilemap-89": "spring tilemap-89.png",
    "spring tilemap-90": "spring tilemap-90.png",
    "spring tilemap-91": "spring tilemap-91.png",
    "spring tilemap-92": "spring tilemap-92.png",
    "spring tilemap-93": "spring tilemap-93.png",
    "spring tilemap-94": "spring tilemap-94.png",
    "spring tilemap-95": "spring tilemap-95.png",
    "spring tilemap-96": "spring tilemap-96.png",
    "spring tilemap-97": "spring tilemap-97.png",
    "spring tilemap-98": "spring tilemap-98.png",
    "spring tilemap-99": "spring tilemap-99.png",
    "spring tilemap-100": "spring tilemap-100.png",
    "spring tilemap-101": "spring tilemap-101.png",
    "spring tilemap-102": "spring tilemap-102.png",
    "spring tilemap-103": "spring tilemap-103.png",
    "spring tilemap-104": "spring tilemap-104.png",
    "spring tilemap-105": "spring tilemap-105.png",
    "spring tilemap-106": "spring tilemap-106.png",
    "spring tilemap-107": "spring tilemap-107.png",
    "spring tilemap-108": "spring tilemap-108.png",
  },
  "summer and spring items": {
    "summer and spring items-0": "summer and spring items-0.png",
    "summer and spring items-1": "summer and spring items-1.png",
    "summer and spring items-2": "summer and spring items-2.png",
    "summer and spring items-3": "summer and spring items-3.png",
    "summer and spring items-4": "summer and spring items-4.png",
    "summer and spring items-5": "summer and spring items-5.png",
    "summer and spring items-6": "summer and spring items-6.png",
    "summer and spring items-7": "summer and spring items-7.png",
    "summer and spring items-8": "summer and spring items-8.png",
    "summer and spring items-9": "summer and spring items-9.png",
    "summer and spring items-10": "summer and spring items-10.png",
    "summer and spring items-11": "summer and spring items-11.png",
    "summer and spring items-12": "summer and spring items-12.png",
    "summer and spring items-13": "summer and spring items-13.png",
    "summer and spring items-14": "summer and spring items-14.png",
    "summer and spring items-15": "summer and spring items-15.png",
    "summer and spring items-16": "summer and spring items-16.png",
    "summer and spring items-17": "summer and spring items-17.png",
    "summer and spring items-18": "summer and spring items-18.png",
    "summer and spring items-19": "summer and spring items-19.png",
    "summer and spring items-20": "summer and spring items-20.png",
    "summer and spring items-21": "summer and spring items-21.png",
    "summer and spring items-22": "summer and spring items-22.png",
    "summer and spring items-23": "summer and spring items-23.png",
    "summer and spring items-24": "summer and spring items-24.png",
    "summer and spring items-25": "summer and spring items-25.png",
    "summer and spring items-26": "summer and spring items-26.png",
    "summer and spring items-27": "summer and spring items-27.png",
    "summer and spring items-28": "summer and spring items-28.png",
    "summer and spring items-29": "summer and spring items-29.png",
    "summer and spring items-30": "summer and spring items-30.png",
    "summer and spring items-31": "summer and spring items-31.png",
    "summer and spring items-32": "summer and spring items-32.png",
    "summer and spring items-33": "summer and spring items-33.png",
    "summer and spring items-34": "summer and spring items-34.png",
    "summer and spring items-35": "summer and spring items-35.png",
    "summer and spring items-36": "summer and spring items-36.png",
    "summer and spring items-37": "summer and spring items-37.png",
    "summer and spring items-38": "summer and spring items-38.png",
    "summer and spring items-39": "summer and spring items-39.png",
    "summer and spring items-40": "summer and spring items-40.png",
    "summer and spring items-41": "summer and spring items-41.png",
    "summer and spring items-42": "summer and spring items-42.png",
    "summer and spring items-43": "summer and spring items-43.png",
    "summer and spring items-44": "summer and spring items-44.png",
    "summer and spring items-45": "summer and spring items-45.png",
    "summer and spring items-46": "summer and spring items-46.png",
    "summer and spring items-47": "summer and spring items-47.png",
    "summer and spring items-48": "summer and spring items-48.png",
    "summer and spring items-49": "summer and spring items-49.png",
    "summer and spring items-50": "summer and spring items-50.png",
    "summer and spring items-51": "summer and spring items-51.png",
    "summer and spring items-52": "summer and spring items-52.png",
    "summer and spring items-53": "summer and spring items-53.png",
    "summer and spring items-54": "summer and spring items-54.png",
    "summer and spring items-55": "summer and spring items-55.png",
    "summer and spring items-56": "summer and spring items-56.png",
    "summer and spring items-57": "summer and spring items-57.png",
    "summer and spring items-58": "summer and spring items-58.png",
    "summer and spring items-59": "summer and spring items-59.png",
    "summer and spring items-60": "summer and spring items-60.png",
    "summer and spring items-61": "summer and spring items-61.png",
    "summer and spring items-62": "summer and spring items-62.png",
    "summer and spring items-63": "summer and spring items-63.png",
    "summer and spring items-64": "summer and spring items-64.png",
    "summer and spring items-65": "summer and spring items-65.png",
    "summer and spring items-66": "summer and spring items-66.png",
    "summer and spring items-67": "summer and spring items-67.png",
    "summer and spring items-68": "summer and spring items-68.png",
    "summer and spring items-69": "summer and spring items-69.png",
    "summer and spring items-70": "summer and spring items-70.png",
    "summer and spring items-71": "summer and spring items-71.png",
    "summer and spring items-72": "summer and spring items-72.png",
    "summer and spring items-73": "summer and spring items-73.png",
    "summer and spring items-74": "summer and spring items-74.png",
    "summer and spring items-75": "summer and spring items-75.png",
    "summer and spring items-76": "summer and spring items-76.png",
    "summer and spring items-77": "summer and spring items-77.png",
    "summer and spring items-78": "summer and spring items-78.png",
    "summer and spring items-79": "summer and spring items-79.png",
    "summer and spring items-80": "summer and spring items-80.png",
    "summer and spring items-81": "summer and spring items-81.png",
    "summer and spring items-82": "summer and spring items-82.png",
    "summer and spring items-83": "summer and spring items-83.png",
    "summer and spring items-84": "summer and spring items-84.png",
    "summer and spring items-85": "summer and spring items-85.png",
    "summer and spring items-86": "summer and spring items-86.png",
    "summer and spring items-87": "summer and spring items-87.png",
    "summer and spring items-88": "summer and spring items-88.png",
    "summer and spring items-89": "summer and spring items-89.png",
    "summer and spring items-90": "summer and spring items-90.png",
    "summer and spring items-91": "summer and spring items-91.png",
    "summer and spring items-92": "summer and spring items-92.png",
    "summer and spring items-93": "summer and spring items-93.png",
    "summer and spring items-94": "summer and spring items-94.png",
    "summer and spring items-95": "summer and spring items-95.png",
    "summer and spring items-96": "summer and spring items-96.png",
    "summer and spring items-97": "summer and spring items-97.png",
    "summer and spring items-98": "summer and spring items-98.png",
    "summer and spring items-99": "summer and spring items-99.png",
    "summer and spring items-100": "summer and spring items-100.png",
    "summer and spring items-101": "summer and spring items-101.png",
    "summer and spring items-102": "summer and spring items-102.png",
    "summer and spring items-103": "summer and spring items-103.png",
    "summer and spring items-104": "summer and spring items-104.png",
    "summer and spring items-105": "summer and spring items-105.png",
    "summer and spring items-106": "summer and spring items-106.png",
    "summer and spring items-107": "summer and spring items-107.png",
    "summer and spring items-108": "summer and spring items-108.png",
    "summer and spring items-109": "summer and spring items-109.png",
    "summer and spring items-110": "summer and spring items-110.png",
    "summer and spring items-111": "summer and spring items-111.png",
    "summer and spring items-112": "summer and spring items-112.png",
    "summer and spring items-113": "summer and spring items-113.png",
    "summer and spring items-114": "summer and spring items-114.png",
    "summer and spring items-115": "summer and spring items-115.png",
    "summer and spring items-116": "summer and spring items-116.png",
    "summer and spring items-117": "summer and spring items-117.png",
    "summer and spring items-118": "summer and spring items-118.png",
    "summer and spring items-119": "summer and spring items-119.png",
    "summer and spring items-120": "summer and spring items-120.png",
    "summer and spring items-121": "summer and spring items-121.png",
    "summer and spring items-122": "summer and spring items-122.png",
    "summer and spring items-123": "summer and spring items-123.png",
    "summer and spring items-124": "summer and spring items-124.png",
    "summer and spring items-125": "summer and spring items-125.png",
    "summer and spring items-126": "summer and spring items-126.png",
    "summer and spring items-127": "summer and spring items-127.png",
    "summer and spring items-128": "summer and spring items-128.png",
    "summer and spring items-129": "summer and spring items-129.png",
    "summer and spring items-130": "summer and spring items-130.png",
    "summer and spring items-131": "summer and spring items-131.png",
    "summer and spring items-132": "summer and spring items-132.png",
    "summer and spring items-133": "summer and spring items-133.png",
    "summer and spring items-134": "summer and spring items-134.png",
    "summer and spring items-135": "summer and spring items-135.png",
    "summer and spring items-136": "summer and spring items-136.png",
    "summer and spring items-137": "summer and spring items-137.png",
    "summer and spring items-138": "summer and spring items-138.png",
    "summer and spring items-139": "summer and spring items-139.png",
    "summer and spring items-140": "summer and spring items-140.png",
    "summer and spring items-141": "summer and spring items-141.png",
    "summer and spring items-142": "summer and spring items-142.png",
    "summer and spring items-143": "summer and spring items-143.png",
    "summer and spring items-144": "summer and spring items-144.png",
    "summer and spring items-145": "summer and spring items-145.png",
    "summer and spring items-146": "summer and spring items-146.png",
    "summer and spring items-147": "summer and spring items-147.png",
    "summer and spring items-148": "summer and spring items-148.png",
    "summer and spring items-149": "summer and spring items-149.png",
  },
  "summer tilemap": {
    "summer tilemap-0": "summer tilemap-0.png",
    "summer tilemap-1": "summer tilemap-1.png",
    "summer tilemap-2": "summer tilemap-2.png",
    "summer tilemap-3": "summer tilemap-3.png",
    "summer tilemap-4": "summer tilemap-4.png",
    "summer tilemap-5": "summer tilemap-5.png",
    "summer tilemap-6": "summer tilemap-6.png",
    "summer tilemap-7": "summer tilemap-7.png",
    "summer tilemap-8": "summer tilemap-8.png",
    "summer tilemap-9": "summer tilemap-9.png",
    "summer tilemap-10": "summer tilemap-10.png",
    "summer tilemap-11": "summer tilemap-11.png",
    "summer tilemap-12": "summer tilemap-12.png",
    "summer tilemap-13": "summer tilemap-13.png",
    "summer tilemap-14": "summer tilemap-14.png",
    "summer tilemap-15": "summer tilemap-15.png",
    "summer tilemap-16": "summer tilemap-16.png",
    "summer tilemap-17": "summer tilemap-17.png",
    "summer tilemap-18": "summer tilemap-18.png",
    "summer tilemap-19": "summer tilemap-19.png",
    "summer tilemap-20": "summer tilemap-20.png",
    "summer tilemap-21": "summer tilemap-21.png",
    "summer tilemap-22": "summer tilemap-22.png",
    "summer tilemap-23": "summer tilemap-23.png",
    "summer tilemap-24": "summer tilemap-24.png",
    "summer tilemap-25": "summer tilemap-25.png",
    "summer tilemap-26": "summer tilemap-26.png",
    "summer tilemap-27": "summer tilemap-27.png",
    "summer tilemap-28": "summer tilemap-28.png",
    "summer tilemap-29": "summer tilemap-29.png",
    "summer tilemap-30": "summer tilemap-30.png",
    "summer tilemap-31": "summer tilemap-31.png",
    "summer tilemap-32": "summer tilemap-32.png",
    "summer tilemap-33": "summer tilemap-33.png",
    "summer tilemap-34": "summer tilemap-34.png",
    "summer tilemap-35": "summer tilemap-35.png",
    "summer tilemap-36": "summer tilemap-36.png",
    "summer tilemap-37": "summer tilemap-37.png",
    "summer tilemap-38": "summer tilemap-38.png",
    "summer tilemap-39": "summer tilemap-39.png",
    "summer tilemap-40": "summer tilemap-40.png",
    "summer tilemap-41": "summer tilemap-41.png",
    "summer tilemap-42": "summer tilemap-42.png",
    "summer tilemap-43": "summer tilemap-43.png",
    "summer tilemap-44": "summer tilemap-44.png",
    "summer tilemap-45": "summer tilemap-45.png",
    "summer tilemap-46": "summer tilemap-46.png",
    "summer tilemap-47": "summer tilemap-47.png",
    "summer tilemap-48": "summer tilemap-48.png",
    "summer tilemap-49": "summer tilemap-49.png",
    "summer tilemap-50": "summer tilemap-50.png",
    "summer tilemap-51": "summer tilemap-51.png",
    "summer tilemap-52": "summer tilemap-52.png",
    "summer tilemap-53": "summer tilemap-53.png",
    "summer tilemap-54": "summer tilemap-54.png",
    "summer tilemap-55": "summer tilemap-55.png",
    "summer tilemap-56": "summer tilemap-56.png",
    "summer tilemap-57": "summer tilemap-57.png",
    "summer tilemap-58": "summer tilemap-58.png",
    "summer tilemap-59": "summer tilemap-59.png",
    "summer tilemap-60": "summer tilemap-60.png",
    "summer tilemap-61": "summer tilemap-61.png",
    "summer tilemap-62": "summer tilemap-62.png",
    "summer tilemap-63": "summer tilemap-63.png",
    "summer tilemap-64": "summer tilemap-64.png",
    "summer tilemap-65": "summer tilemap-65.png",
    "summer tilemap-66": "summer tilemap-66.png",
    "summer tilemap-67": "summer tilemap-67.png",
    "summer tilemap-68": "summer tilemap-68.png",
    "summer tilemap-69": "summer tilemap-69.png",
    "summer tilemap-70": "summer tilemap-70.png",
    "summer tilemap-71": "summer tilemap-71.png",
    "summer tilemap-72": "summer tilemap-72.png",
    "summer tilemap-73": "summer tilemap-73.png",
    "summer tilemap-74": "summer tilemap-74.png",
    "summer tilemap-75": "summer tilemap-75.png",
    "summer tilemap-76": "summer tilemap-76.png",
    "summer tilemap-77": "summer tilemap-77.png",
    "summer tilemap-78": "summer tilemap-78.png",
    "summer tilemap-79": "summer tilemap-79.png",
    "summer tilemap-80": "summer tilemap-80.png",
    "summer tilemap-81": "summer tilemap-81.png",
    "summer tilemap-82": "summer tilemap-82.png",
    "summer tilemap-83": "summer tilemap-83.png",
    "summer tilemap-84": "summer tilemap-84.png",
    "summer tilemap-85": "summer tilemap-85.png",
    "summer tilemap-86": "summer tilemap-86.png",
    "summer tilemap-87": "summer tilemap-87.png",
    "summer tilemap-88": "summer tilemap-88.png",
    "summer tilemap-89": "summer tilemap-89.png",
    "summer tilemap-90": "summer tilemap-90.png",
    "summer tilemap-91": "summer tilemap-91.png",
    "summer tilemap-92": "summer tilemap-92.png",
    "summer tilemap-93": "summer tilemap-93.png",
    "summer tilemap-94": "summer tilemap-94.png",
    "summer tilemap-95": "summer tilemap-95.png",
    "summer tilemap-96": "summer tilemap-96.png",
    "summer tilemap-97": "summer tilemap-97.png",
    "summer tilemap-98": "summer tilemap-98.png",
    "summer tilemap-99": "summer tilemap-99.png",
    "summer tilemap-100": "summer tilemap-100.png",
    "summer tilemap-101": "summer tilemap-101.png",
    "summer tilemap-102": "summer tilemap-102.png",
    "summer tilemap-103": "summer tilemap-103.png",
    "summer tilemap-104": "summer tilemap-104.png",
    "summer tilemap-105": "summer tilemap-105.png",
    "summer tilemap-106": "summer tilemap-106.png",
    "summer tilemap-107": "summer tilemap-107.png",
    "summer tilemap-108": "summer tilemap-108.png",
  },
  sword: {
    "sword-0": "sword-0.png",
    "sword-1": "sword-1.png",
    "sword-2": "sword-2.png",
    "sword-3": "sword-3.png",
    "sword-4": "sword-4.png",
    "sword-5": "sword-5.png",
    "sword-6": "sword-6.png",
    "sword-7": "sword-7.png",
  },
  "walk and idle": {
    "walk and idle-0": "walk and idle-0.png",
    "walk and idle-1": "walk and idle-1.png",
    "walk and idle-2": "walk and idle-2.png",
    "walk and idle-3": "walk and idle-3.png",
    "walk and idle-4": "walk and idle-4.png",
    "walk and idle-5": "walk and idle-5.png",
    "walk and idle-6": "walk and idle-6.png",
    "walk and idle-7": "walk and idle-7.png",
    "walk and idle-8": "walk and idle-8.png",
    "walk and idle-9": "walk and idle-9.png",
    "walk and idle-10": "walk and idle-10.png",
    "walk and idle-11": "walk and idle-11.png",
    "walk and idle-12": "walk and idle-12.png",
    "walk and idle-13": "walk and idle-13.png",
    "walk and idle-14": "walk and idle-14.png",
    "walk and idle-15": "walk and idle-15.png",
    "walk and idle-16": "walk and idle-16.png",
    "walk and idle-17": "walk and idle-17.png",
    "walk and idle-18": "walk and idle-18.png",
    "walk and idle-19": "walk and idle-19.png",
  },
  "winter items": {
    "winter items-0": "winter items-0.png",
    "winter items-1": "winter items-1.png",
    "winter items-2": "winter items-2.png",
    "winter items-3": "winter items-3.png",
    "winter items-4": "winter items-4.png",
    "winter items-5": "winter items-5.png",
    "winter items-6": "winter items-6.png",
    "winter items-7": "winter items-7.png",
    "winter items-8": "winter items-8.png",
    "winter items-9": "winter items-9.png",
    "winter items-10": "winter items-10.png",
    "winter items-11": "winter items-11.png",
    "winter items-12": "winter items-12.png",
    "winter items-13": "winter items-13.png",
    "winter items-14": "winter items-14.png",
    "winter items-15": "winter items-15.png",
    "winter items-16": "winter items-16.png",
    "winter items-17": "winter items-17.png",
    "winter items-18": "winter items-18.png",
    "winter items-19": "winter items-19.png",
    "winter items-20": "winter items-20.png",
    "winter items-21": "winter items-21.png",
    "winter items-22": "winter items-22.png",
    "winter items-23": "winter items-23.png",
    "winter items-24": "winter items-24.png",
    "winter items-25": "winter items-25.png",
    "winter items-26": "winter items-26.png",
    "winter items-27": "winter items-27.png",
    "winter items-28": "winter items-28.png",
    "winter items-29": "winter items-29.png",
    "winter items-30": "winter items-30.png",
    "winter items-31": "winter items-31.png",
    "winter items-32": "winter items-32.png",
    "winter items-33": "winter items-33.png",
    "winter items-34": "winter items-34.png",
    "winter items-35": "winter items-35.png",
    "winter items-36": "winter items-36.png",
    "winter items-37": "winter items-37.png",
    "winter items-38": "winter items-38.png",
    "winter items-39": "winter items-39.png",
    "winter items-40": "winter items-40.png",
    "winter items-41": "winter items-41.png",
    "winter items-42": "winter items-42.png",
    "winter items-43": "winter items-43.png",
    "winter items-44": "winter items-44.png",
    "winter items-45": "winter items-45.png",
    "winter items-46": "winter items-46.png",
    "winter items-47": "winter items-47.png",
    "winter items-48": "winter items-48.png",
    "winter items-49": "winter items-49.png",
    "winter items-50": "winter items-50.png",
    "winter items-51": "winter items-51.png",
    "winter items-52": "winter items-52.png",
    "winter items-53": "winter items-53.png",
    "winter items-54": "winter items-54.png",
    "winter items-55": "winter items-55.png",
    "winter items-56": "winter items-56.png",
    "winter items-57": "winter items-57.png",
    "winter items-58": "winter items-58.png",
    "winter items-59": "winter items-59.png",
    "winter items-60": "winter items-60.png",
    "winter items-61": "winter items-61.png",
    "winter items-62": "winter items-62.png",
    "winter items-63": "winter items-63.png",
    "winter items-64": "winter items-64.png",
    "winter items-65": "winter items-65.png",
    "winter items-66": "winter items-66.png",
    "winter items-67": "winter items-67.png",
    "winter items-68": "winter items-68.png",
    "winter items-69": "winter items-69.png",
    "winter items-70": "winter items-70.png",
    "winter items-71": "winter items-71.png",
    "winter items-72": "winter items-72.png",
    "winter items-73": "winter items-73.png",
    "winter items-74": "winter items-74.png",
    "winter items-75": "winter items-75.png",
    "winter items-76": "winter items-76.png",
    "winter items-77": "winter items-77.png",
    "winter items-78": "winter items-78.png",
    "winter items-79": "winter items-79.png",
    "winter items-80": "winter items-80.png",
    "winter items-81": "winter items-81.png",
    "winter items-82": "winter items-82.png",
    "winter items-83": "winter items-83.png",
    "winter items-84": "winter items-84.png",
    "winter items-85": "winter items-85.png",
    "winter items-86": "winter items-86.png",
    "winter items-87": "winter items-87.png",
    "winter items-88": "winter items-88.png",
    "winter items-89": "winter items-89.png",
    "winter items-90": "winter items-90.png",
    "winter items-91": "winter items-91.png",
    "winter items-92": "winter items-92.png",
  },
  "winter outside": {
    "winter outside-0": "winter outside-0.png",
    "winter outside-1": "winter outside-1.png",
    "winter outside-2": "winter outside-2.png",
    "winter outside-3": "winter outside-3.png",
    "winter outside-4": "winter outside-4.png",
    "winter outside-5": "winter outside-5.png",
    "winter outside-6": "winter outside-6.png",
    "winter outside-7": "winter outside-7.png",
    "winter outside-8": "winter outside-8.png",
    "winter outside-9": "winter outside-9.png",
    "winter outside-10": "winter outside-10.png",
    "winter outside-11": "winter outside-11.png",
    "winter outside-12": "winter outside-12.png",
    "winter outside-13": "winter outside-13.png",
    "winter outside-14": "winter outside-14.png",
    "winter outside-15": "winter outside-15.png",
    "winter outside-16": "winter outside-16.png",
    "winter outside-17": "winter outside-17.png",
    "winter outside-18": "winter outside-18.png",
    "winter outside-19": "winter outside-19.png",
    "winter outside-20": "winter outside-20.png",
    "winter outside-21": "winter outside-21.png",
    "winter outside-22": "winter outside-22.png",
    "winter outside-23": "winter outside-23.png",
    "winter outside-24": "winter outside-24.png",
    "winter outside-25": "winter outside-25.png",
    "winter outside-26": "winter outside-26.png",
    "winter outside-27": "winter outside-27.png",
    "winter outside-28": "winter outside-28.png",
    "winter outside-29": "winter outside-29.png",
    "winter outside-30": "winter outside-30.png",
    "winter outside-31": "winter outside-31.png",
    "winter outside-32": "winter outside-32.png",
    "winter outside-33": "winter outside-33.png",
    "winter outside-34": "winter outside-34.png",
    "winter outside-35": "winter outside-35.png",
    "winter outside-36": "winter outside-36.png",
    "winter outside-37": "winter outside-37.png",
    "winter outside-38": "winter outside-38.png",
    "winter outside-39": "winter outside-39.png",
    "winter outside-40": "winter outside-40.png",
    "winter outside-41": "winter outside-41.png",
    "winter outside-42": "winter outside-42.png",
    "winter outside-43": "winter outside-43.png",
    "winter outside-44": "winter outside-44.png",
    "winter outside-45": "winter outside-45.png",
    "winter outside-46": "winter outside-46.png",
    "winter outside-47": "winter outside-47.png",
    "winter outside-48": "winter outside-48.png",
    "winter outside-49": "winter outside-49.png",
    "winter outside-50": "winter outside-50.png",
    "winter outside-51": "winter outside-51.png",
    "winter outside-52": "winter outside-52.png",
    "winter outside-53": "winter outside-53.png",
    "winter outside-54": "winter outside-54.png",
    "winter outside-55": "winter outside-55.png",
    "winter outside-56": "winter outside-56.png",
    "winter outside-57": "winter outside-57.png",
    "winter outside-58": "winter outside-58.png",
    "winter outside-59": "winter outside-59.png",
    "winter outside-60": "winter outside-60.png",
    "winter outside-61": "winter outside-61.png",
    "winter outside-62": "winter outside-62.png",
    "winter outside-63": "winter outside-63.png",
    "winter outside-64": "winter outside-64.png",
    "winter outside-65": "winter outside-65.png",
    "winter outside-66": "winter outside-66.png",
    "winter outside-67": "winter outside-67.png",
    "winter outside-68": "winter outside-68.png",
    "winter outside-69": "winter outside-69.png",
    "winter outside-70": "winter outside-70.png",
    "winter outside-71": "winter outside-71.png",
    "winter outside-72": "winter outside-72.png",
    "winter outside-73": "winter outside-73.png",
    "winter outside-74": "winter outside-74.png",
    "winter outside-75": "winter outside-75.png",
    "winter outside-76": "winter outside-76.png",
    "winter outside-77": "winter outside-77.png",
    "winter outside-78": "winter outside-78.png",
    "winter outside-79": "winter outside-79.png",
    "winter outside-80": "winter outside-80.png",
    "winter outside-81": "winter outside-81.png",
    "winter outside-82": "winter outside-82.png",
    "winter outside-83": "winter outside-83.png",
    "winter outside-84": "winter outside-84.png",
    "winter outside-85": "winter outside-85.png",
    "winter outside-86": "winter outside-86.png",
    "winter outside-87": "winter outside-87.png",
    "winter outside-88": "winter outside-88.png",
    "winter outside-89": "winter outside-89.png",
    "winter outside-90": "winter outside-90.png",
    "winter outside-91": "winter outside-91.png",
    "winter outside-92": "winter outside-92.png",
    "winter outside-93": "winter outside-93.png",
    "winter outside-94": "winter outside-94.png",
    "winter outside-95": "winter outside-95.png",
    "winter outside-96": "winter outside-96.png",
    "winter outside-97": "winter outside-97.png",
    "winter outside-98": "winter outside-98.png",
    "winter outside-99": "winter outside-99.png",
    "winter outside-100": "winter outside-100.png",
    "winter outside-101": "winter outside-101.png",
    "winter outside-102": "winter outside-102.png",
    "winter outside-103": "winter outside-103.png",
    "winter outside-104": "winter outside-104.png",
    "winter outside-105": "winter outside-105.png",
    "winter outside-106": "winter outside-106.png",
    "winter outside-107": "winter outside-107.png",
    "winter outside-108": "winter outside-108.png",
    "winter outside-109": "winter outside-109.png",
    "winter outside-110": "winter outside-110.png",
    "winter outside-111": "winter outside-111.png",
    "winter outside-112": "winter outside-112.png",
    "winter outside-113": "winter outside-113.png",
    "winter outside-114": "winter outside-114.png",
  },
};
